<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\WeddingLanding.Core\WeddingLanding.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>0e57b65c-3f8c-40aa-a159-0679f40f080f</UserSecretsId>
  </PropertyGroup>

</Project>
